// AUTO-GENERATED by build.py — do not edit by hand.
// Re-run `python3 build.py` to regenerate.
const players = {
  "lazar": {
    "name": "Lazar Djokovic",
    "number": 17,
    "position": "C",
    "primary_position": "C",
    "year_abbr": "Jr",
    "year": "Junior",
    "height": "6-11",
    "weight": 235,
    "hometown": "Gornji Milanovac, Serbia",
    "team": "VCU",
    "season": "2025-26",
    "games": 35,
    "kenpom": {
      "minPct": 67.1,
      "ortg": 120.6,
      "possPct": 21.9,
      "shotsPct": 19.4,
      "efg": 54.2,
      "ts": 61.8,
      "orPct": 7.6,
      "drPct": 13.5,
      "aRate": 7.3,
      "toRate": 13.9,
      "blkPct": 4.5,
      "stlPct": 1.1,
      "fc40": 3.0,
      "fd40": 6.1,
      "ftRate": 77.4,
      "ft": {
        "made": 166,
        "att": 212,
        "pct": 0.783
      },
      "twoP": {
        "made": 114,
        "att": 207,
        "pct": 0.551
      },
      "threeP": {
        "made": 23,
        "att": 67,
        "pct": 0.34
      }
    },
    "key": "lazar",
    "photo": "photos/lazar.png",
    "playTypes": [
      {
        "name": "Post-Up",
        "poss": 95,
        "timePct": 22.7,
        "pps": 1.011,
        "efg": 46.6,
        "verdict": "Very Good",
        "percentile": 75,
        "subs": []
      },
      {
        "name": "Spot Up",
        "poss": 85,
        "timePct": 20.3,
        "pps": 1.047,
        "efg": 50.0,
        "verdict": "Very Good",
        "percentile": 71,
        "subs": [
          {
            "name": "No Dribble Jumper",
            "poss": 42,
            "timePct": 49.4,
            "pps": 0.976,
            "efg": 47.6
          },
          {
            "name": "Drives Right",
            "poss": 32,
            "timePct": 37.6,
            "pps": 1.063,
            "efg": 52.6
          },
          {
            "name": "Drives Left",
            "poss": 11,
            "timePct": 12.9,
            "pps": 1.273,
            "efg": 57.1
          },
          {
            "name": "Turnover",
            "poss": 9,
            "timePct": 40.9,
            "pps": 0.0,
            "efg": null
          }
        ]
      },
      {
        "name": "Transition",
        "poss": 60,
        "timePct": 14.3,
        "pps": 1.3,
        "efg": 69.0,
        "verdict": "Excellent",
        "percentile": 84,
        "subs": [
          {
            "name": "Ballhandler",
            "poss": 2,
            "timePct": 3.3,
            "pps": 1.0,
            "efg": 50.0
          },
          {
            "name": "Right Wing",
            "poss": 9,
            "timePct": 15.0,
            "pps": 1.111,
            "efg": 58.3
          },
          {
            "name": "Left Wing",
            "poss": 22,
            "timePct": 36.7,
            "pps": 1.318,
            "efg": 75.0
          },
          {
            "name": "Trailer",
            "poss": 13,
            "timePct": 21.7,
            "pps": 1.462,
            "efg": 72.2
          },
          {
            "name": "Leak Outs",
            "poss": 3,
            "timePct": 5.0,
            "pps": 1.333,
            "efg": 66.7
          },
          {
            "name": "First Middle",
            "poss": 10,
            "timePct": 16.7,
            "pps": 1.4,
            "efg": 68.8
          }
        ]
      },
      {
        "name": "P&R Roll Man",
        "poss": 51,
        "timePct": 12.2,
        "pps": 1.176,
        "efg": 54.2,
        "verdict": "Very Good",
        "percentile": 69,
        "subs": []
      },
      {
        "name": "Cut",
        "poss": 50,
        "timePct": 11.9,
        "pps": 1.34,
        "efg": 62.9,
        "verdict": "Very Good",
        "percentile": 72,
        "subs": []
      },
      {
        "name": "Offensive Rebounds (Put Backs)",
        "poss": 32,
        "timePct": 7.6,
        "pps": 1.281,
        "efg": 61.9,
        "verdict": "Very Good",
        "percentile": 74,
        "subs": []
      },
      {
        "name": "Miscellaneous Plays",
        "poss": 22,
        "timePct": 5.3,
        "pps": 0.909,
        "efg": 100.0,
        "verdict": "Excellent",
        "percentile": 90,
        "subs": []
      },
      {
        "name": "P&R Ball Handler",
        "poss": 10,
        "timePct": 2.4,
        "pps": 0.6,
        "efg": 25.0,
        "verdict": "Below Average",
        "percentile": 20,
        "subs": []
      },
      {
        "name": "Handoffs",
        "poss": 6,
        "timePct": 1.4,
        "pps": 0.0,
        "efg": 0.0,
        "verdict": null,
        "percentile": null,
        "subs": []
      },
      {
        "name": "Isolation",
        "poss": 5,
        "timePct": 1.2,
        "pps": 0.6,
        "efg": 0.0,
        "verdict": null,
        "percentile": null,
        "subs": []
      },
      {
        "name": "Off Screen",
        "poss": 3,
        "timePct": 0.7,
        "pps": 0.0,
        "efg": 0.0,
        "verdict": null,
        "percentile": null,
        "subs": []
      }
    ],
    "shotTypes": [
      {
        "name": "Jump Shot",
        "poss": 73,
        "timePct": 26.6,
        "pps": 0.99,
        "efg": 49.3,
        "verdict": "Good",
        "percentile": 61,
        "subs": [
          {
            "name": "Catch and Shoot",
            "poss": 67,
            "timePct": 91.8,
            "pps": 0.94,
            "efg": 47.0,
            "subs": [
              {
                "name": "Guarded",
                "poss": 41,
                "timePct": 61.2,
                "pps": 1.02,
                "efg": 51.2
              },
              {
                "name": "Unguarded",
                "poss": 26,
                "timePct": 38.8,
                "pps": 0.81,
                "efg": 40.4
              }
            ]
          },
          {
            "name": "Dribble Jumper",
            "poss": 5,
            "timePct": 6.8,
            "pps": 1.4,
            "efg": 70.0,
            "subs": []
          },
          {
            "name": "Early Jumper",
            "poss": 0,
            "timePct": 0.0,
            "pps": null,
            "efg": null,
            "subs": []
          }
        ]
      },
      {
        "name": "At Rim",
        "poss": 151,
        "timePct": 55.1,
        "pps": 1.21,
        "efg": 60.3,
        "verdict": "Good",
        "percentile": 61,
        "subs": [
          {
            "name": "Layup",
            "poss": 108,
            "timePct": 71.5,
            "pps": 1.02,
            "efg": 50.9,
            "subs": []
          },
          {
            "name": "Dunk",
            "poss": 37,
            "timePct": 24.5,
            "pps": 1.78,
            "efg": 89.2,
            "subs": []
          },
          {
            "name": "Tip",
            "poss": 6,
            "timePct": 4.0,
            "pps": 1.0,
            "efg": 50.0,
            "subs": []
          }
        ]
      },
      {
        "name": "Runner",
        "poss": 11,
        "timePct": 4.0,
        "pps": 0.91,
        "efg": 45.5,
        "verdict": "Very Good",
        "percentile": 69,
        "subs": []
      },
      {
        "name": "Hook",
        "poss": 27,
        "timePct": 9.9,
        "pps": 0.81,
        "efg": 40.7,
        "verdict": "Average",
        "percentile": 37,
        "subs": []
      }
    ],
    "shotZones": {
      "restrictedArea": {
        "volume": 42.9,
        "efg": 55.6,
        "poss": 36
      },
      "paint": {
        "volume": 21.4,
        "efg": 22.2,
        "poss": 18
      },
      "midrange": {
        "volume": 1.2,
        "efg": 100.0,
        "poss": 1
      },
      "beyondArc": {
        "volume": 34.5,
        "efg": 46.6,
        "poss": 29
      }
    },
    "archetype": "High-Volume Stretch 5",
    "analysis": [
      "34.3% from 3 on 67 attempts alongside 1.011 PPS Post-Up",
      "120.6 ORtg on 21.9% usage",
      "6.1 FD/40, 77.4 FTRate, 78.3% FT, elite at drawing fouls and converting"
    ]
  },
  "evans": {
    "name": "Barry Evans",
    "number": 5,
    "position": "PF",
    "primary_position": "PF",
    "year_abbr": "Sr",
    "year": "Senior",
    "height": "6-8",
    "weight": 215,
    "hometown": "Baltimore, MD",
    "team": "VCU",
    "season": "2025-26",
    "games": 36,
    "kenpom": {
      "minPct": 66.1,
      "ortg": 110.7,
      "possPct": 16.0,
      "shotsPct": 17.2,
      "efg": 50.2,
      "ts": 50.6,
      "orPct": 7.4,
      "drPct": 13.2,
      "aRate": 14.4,
      "toRate": 14.7,
      "blkPct": 1.9,
      "stlPct": 2.0,
      "fc40": 2.4,
      "fd40": 1.9,
      "ftRate": 15.1,
      "ft": {
        "made": 19,
        "att": 36,
        "pct": 0.528
      },
      "twoP": {
        "made": 81,
        "att": 157,
        "pct": 0.516
      },
      "threeP": {
        "made": 26,
        "att": 82,
        "pct": 0.317
      }
    },
    "key": "evans",
    "photo": "photos/evans.png",
    "playTypes": [
      {
        "name": "Spot Up",
        "poss": 98,
        "timePct": 33.4,
        "pps": 0.816,
        "efg": 45.3,
        "verdict": "Below Average",
        "percentile": 28,
        "subs": [
          {
            "name": "No Dribble Jumper",
            "poss": 57,
            "timePct": 58.2,
            "pps": 0.93,
            "efg": 46.5
          },
          {
            "name": "Drives Right",
            "poss": 29,
            "timePct": 29.6,
            "pps": 0.724,
            "efg": 45.2
          },
          {
            "name": "Drives Left",
            "poss": 11,
            "timePct": 11.2,
            "pps": 0.545,
            "efg": 42.9
          },
          {
            "name": "Drives Straight",
            "poss": 1,
            "timePct": 1.0,
            "pps": 0.0,
            "efg": 0.0
          },
          {
            "name": "Turnover",
            "poss": 10,
            "timePct": 66.7,
            "pps": 0.0,
            "efg": null
          }
        ]
      },
      {
        "name": "Transition",
        "poss": 72,
        "timePct": 24.6,
        "pps": 1.194,
        "efg": 69.5,
        "verdict": "Very Good",
        "percentile": 70,
        "subs": [
          {
            "name": "Ballhandler",
            "poss": 30,
            "timePct": 41.7,
            "pps": 1.067,
            "efg": 71.4
          },
          {
            "name": "Right Wing",
            "poss": 22,
            "timePct": 30.6,
            "pps": 1.364,
            "efg": 75.0
          },
          {
            "name": "Left Wing",
            "poss": 6,
            "timePct": 8.3,
            "pps": 0.667,
            "efg": 33.3
          },
          {
            "name": "Trailer",
            "poss": 5,
            "timePct": 6.9,
            "pps": 0.4,
            "efg": 25.0
          },
          {
            "name": "Leak Outs",
            "poss": 6,
            "timePct": 8.3,
            "pps": 2.0,
            "efg": 100.0
          },
          {
            "name": "First Middle",
            "poss": 3,
            "timePct": 4.2,
            "pps": 2.0,
            "efg": 100.0
          }
        ]
      },
      {
        "name": "Offensive Rebounds (Put Backs)",
        "poss": 35,
        "timePct": 11.9,
        "pps": 1.0,
        "efg": 50.0,
        "verdict": "Average",
        "percentile": 32,
        "subs": []
      },
      {
        "name": "Cut",
        "poss": 18,
        "timePct": 6.1,
        "pps": 1.333,
        "efg": 66.7,
        "verdict": "Very Good",
        "percentile": 71,
        "subs": []
      },
      {
        "name": "Miscellaneous Plays",
        "poss": 15,
        "timePct": 5.1,
        "pps": 0.067,
        "efg": 0.0,
        "verdict": "Poor",
        "percentile": 2,
        "subs": []
      },
      {
        "name": "P&R Ball Handler",
        "poss": 14,
        "timePct": 4.8,
        "pps": 0.571,
        "efg": 30.8,
        "verdict": "Below Average",
        "percentile": 16,
        "subs": []
      },
      {
        "name": "Post-Up",
        "poss": 14,
        "timePct": 4.8,
        "pps": 0.571,
        "efg": 30.8,
        "verdict": "Poor",
        "percentile": 9,
        "subs": []
      },
      {
        "name": "Isolation",
        "poss": 12,
        "timePct": 4.1,
        "pps": 0.917,
        "efg": 50.0,
        "verdict": "Very Good",
        "percentile": 65,
        "subs": []
      },
      {
        "name": "P&R Roll Man",
        "poss": 8,
        "timePct": 2.7,
        "pps": 0.25,
        "efg": 14.3,
        "verdict": null,
        "percentile": null,
        "subs": []
      },
      {
        "name": "Off Screen",
        "poss": 4,
        "timePct": 1.4,
        "pps": 0.0,
        "efg": 0.0,
        "verdict": null,
        "percentile": null,
        "subs": []
      },
      {
        "name": "Handoffs",
        "poss": 3,
        "timePct": 1.0,
        "pps": 0.667,
        "efg": 0.0,
        "verdict": null,
        "percentile": null,
        "subs": []
      }
    ],
    "shotTypes": [
      {
        "name": "Jump Shot",
        "poss": 86,
        "timePct": 35.7,
        "pps": 0.92,
        "efg": 45.9,
        "verdict": "Average",
        "percentile": 46,
        "subs": [
          {
            "name": "Catch and Shoot",
            "poss": 78,
            "timePct": 90.7,
            "pps": 0.91,
            "efg": 45.5,
            "subs": [
              {
                "name": "Guarded",
                "poss": 43,
                "timePct": 55.1,
                "pps": 0.81,
                "efg": 40.7
              },
              {
                "name": "Unguarded",
                "poss": 35,
                "timePct": 44.9,
                "pps": 1.03,
                "efg": 51.4
              }
            ]
          },
          {
            "name": "Dribble Jumper",
            "poss": 7,
            "timePct": 8.1,
            "pps": 0.86,
            "efg": 42.9,
            "subs": []
          },
          {
            "name": "Early Jumper",
            "poss": 1,
            "timePct": 1.2,
            "pps": 3.0,
            "efg": 150.0,
            "subs": []
          }
        ]
      },
      {
        "name": "At Rim",
        "poss": 124,
        "timePct": 51.5,
        "pps": 1.11,
        "efg": 55.6,
        "verdict": "Average",
        "percentile": 42,
        "subs": [
          {
            "name": "Layup",
            "poss": 89,
            "timePct": 71.8,
            "pps": 0.9,
            "efg": 44.9,
            "subs": []
          },
          {
            "name": "Dunk",
            "poss": 27,
            "timePct": 21.8,
            "pps": 1.85,
            "efg": 92.6,
            "subs": []
          },
          {
            "name": "Tip",
            "poss": 8,
            "timePct": 6.5,
            "pps": 1.0,
            "efg": 50.0,
            "subs": []
          }
        ]
      },
      {
        "name": "Runner",
        "poss": 20,
        "timePct": 8.3,
        "pps": 0.5,
        "efg": 25.0,
        "verdict": "Poor",
        "percentile": 13,
        "subs": []
      },
      {
        "name": "Hook",
        "poss": 12,
        "timePct": 5.0,
        "pps": 1.17,
        "efg": 58.3,
        "verdict": "Excellent",
        "percentile": 90,
        "subs": []
      }
    ],
    "shotZones": {
      "restrictedArea": {
        "volume": 36.9,
        "efg": 67.7,
        "poss": 31
      },
      "paint": {
        "volume": 22.6,
        "efg": 36.8,
        "poss": 19
      },
      "midrange": {
        "volume": 0.0,
        "efg": null,
        "poss": 0
      },
      "beyondArc": {
        "volume": 40.5,
        "efg": 48.5,
        "poss": 34
      }
    },
    "archetype": "Transition 4",
    "analysis": [
      "31.7% from 3 on 82 attempts despite Spot Up being his top play type by volume",
      "1.194 PPS in Transition (Very Good) is where his offense lives, 0.816 PPS Spot Up (Below Average) is his shortcoming"
    ]
  },
  "hill": {
    "name": "Terrence Hill",
    "number": 6,
    "position": "PG",
    "primary_position": "PG",
    "year_abbr": "So",
    "year": "Sophomore",
    "height": "6-3",
    "weight": 180,
    "hometown": "Portland, OR",
    "team": "VCU",
    "season": "2025-26",
    "games": 36,
    "kenpom": {
      "minPct": 62.4,
      "ortg": 128.3,
      "possPct": 25.0,
      "shotsPct": 28.1,
      "efg": 57.6,
      "ts": 62.4,
      "orPct": 1.4,
      "drPct": 10.4,
      "aRate": 23.8,
      "toRate": 10.2,
      "blkPct": 0.2,
      "stlPct": 1.4,
      "fc40": 2.4,
      "fd40": 4.7,
      "ftRate": 36.0,
      "ft": {
        "made": 114,
        "att": 133,
        "pct": 0.857
      },
      "twoP": {
        "made": 91,
        "att": 150,
        "pct": 0.607
      },
      "threeP": {
        "made": 81,
        "att": 219,
        "pct": 0.37
      }
    },
    "key": "hill",
    "photo": "photos/hill.png",
    "playTypes": [
      {
        "name": "P&R Ball Handler",
        "poss": 140,
        "timePct": 30.1,
        "pps": 0.993,
        "efg": 52.4,
        "verdict": "Excellent",
        "percentile": 84,
        "subs": []
      },
      {
        "name": "Spot Up",
        "poss": 104,
        "timePct": 22.4,
        "pps": 1.327,
        "efg": 63.2,
        "verdict": "Excellent",
        "percentile": 97,
        "subs": [
          {
            "name": "No Dribble Jumper",
            "poss": 3,
            "timePct": 10.3,
            "pps": 1.0,
            "efg": 50.0
          },
          {
            "name": "Drives Right",
            "poss": 20,
            "timePct": 19.2,
            "pps": 0.95,
            "efg": 36.7
          },
          {
            "name": "Drives Left",
            "poss": 14,
            "timePct": 13.5,
            "pps": 1.357,
            "efg": 59.1
          },
          {
            "name": "Drives Straight",
            "poss": 2,
            "timePct": 1.9,
            "pps": 0.0,
            "efg": 0.0
          },
          {
            "name": "Turnover",
            "poss": 6,
            "timePct": 20.7,
            "pps": 0.0,
            "efg": null
          }
        ]
      },
      {
        "name": "Transition",
        "poss": 80,
        "timePct": 17.2,
        "pps": 1.238,
        "efg": 62.9,
        "verdict": "Very Good",
        "percentile": 76,
        "subs": [
          {
            "name": "Ballhandler",
            "poss": 23,
            "timePct": 28.8,
            "pps": 1.087,
            "efg": 62.5
          },
          {
            "name": "Right Wing",
            "poss": 24,
            "timePct": 30.0,
            "pps": 1.375,
            "efg": 65.0
          },
          {
            "name": "Left Wing",
            "poss": 18,
            "timePct": 22.5,
            "pps": 1.111,
            "efg": 52.9
          },
          {
            "name": "Trailer",
            "poss": 8,
            "timePct": 10.0,
            "pps": 1.125,
            "efg": 64.3
          },
          {
            "name": "Leak Outs",
            "poss": 5,
            "timePct": 6.3,
            "pps": 2.0,
            "efg": 100.0
          },
          {
            "name": "First Middle",
            "poss": 2,
            "timePct": 2.5,
            "pps": 1.0,
            "efg": 0.0
          }
        ]
      },
      {
        "name": "Handoffs",
        "poss": 37,
        "timePct": 8.0,
        "pps": 1.081,
        "efg": 62.1,
        "verdict": "Very Good",
        "percentile": 80,
        "subs": []
      },
      {
        "name": "Miscellaneous Plays",
        "poss": 29,
        "timePct": 6.2,
        "pps": 1.241,
        "efg": 56.3,
        "verdict": "Excellent",
        "percentile": 99,
        "subs": []
      },
      {
        "name": "Isolation",
        "poss": 26,
        "timePct": 5.6,
        "pps": 0.885,
        "efg": 40.9,
        "verdict": "Good",
        "percentile": 59,
        "subs": []
      },
      {
        "name": "Off Screen",
        "poss": 26,
        "timePct": 5.6,
        "pps": 0.962,
        "efg": 47.8,
        "verdict": "Good",
        "percentile": 52,
        "subs": []
      },
      {
        "name": "P&R Roll Man",
        "poss": 13,
        "timePct": 2.8,
        "pps": 0.923,
        "efg": 46.2,
        "verdict": "Average",
        "percentile": 32,
        "subs": []
      },
      {
        "name": "Cut",
        "poss": 6,
        "timePct": 1.3,
        "pps": 1.667,
        "efg": 83.3,
        "verdict": null,
        "percentile": null,
        "subs": []
      },
      {
        "name": "Offensive Rebounds (Put Backs)",
        "poss": 3,
        "timePct": 0.6,
        "pps": 2.0,
        "efg": 100.0,
        "verdict": null,
        "percentile": null,
        "subs": []
      },
      {
        "name": "Post-Up",
        "poss": 1,
        "timePct": 0.2,
        "pps": 0.0,
        "efg": 0.0,
        "verdict": null,
        "percentile": null,
        "subs": []
      }
    ],
    "shotTypes": [
      {
        "name": "Jump Shot",
        "poss": 264,
        "timePct": 71.2,
        "pps": 1.11,
        "efg": 55.5,
        "verdict": "Excellent",
        "percentile": 85,
        "subs": [
          {
            "name": "Catch and Shoot",
            "poss": 137,
            "timePct": 51.9,
            "pps": 1.24,
            "efg": 62.0,
            "subs": [
              {
                "name": "Guarded",
                "poss": 90,
                "timePct": 65.7,
                "pps": 1.09,
                "efg": 54.4
              },
              {
                "name": "Unguarded",
                "poss": 47,
                "timePct": 34.3,
                "pps": 1.53,
                "efg": 76.6
              }
            ]
          },
          {
            "name": "Dribble Jumper",
            "poss": 127,
            "timePct": 48.1,
            "pps": 0.97,
            "efg": 48.4,
            "subs": []
          },
          {
            "name": "Early Jumper",
            "poss": 10,
            "timePct": 3.8,
            "pps": 0.3,
            "efg": 15.0,
            "subs": []
          }
        ]
      },
      {
        "name": "At Rim",
        "poss": 93,
        "timePct": 25.1,
        "pps": 1.27,
        "efg": 63.4,
        "verdict": "Very Good",
        "percentile": 73,
        "subs": [
          {
            "name": "Layup",
            "poss": 93,
            "timePct": 100.0,
            "pps": 1.27,
            "efg": 63.4,
            "subs": []
          },
          {
            "name": "Dunk",
            "poss": 0,
            "timePct": 0.0,
            "pps": null,
            "efg": null,
            "subs": []
          },
          {
            "name": "Tip",
            "poss": 0,
            "timePct": 0.0,
            "pps": null,
            "efg": null,
            "subs": []
          }
        ]
      },
      {
        "name": "Runner",
        "poss": 12,
        "timePct": 3.2,
        "pps": 1.0,
        "efg": 50.0,
        "verdict": "Excellent",
        "percentile": 84,
        "subs": []
      },
      {
        "name": "Hook",
        "poss": 1,
        "timePct": 0.3,
        "pps": 2.0,
        "efg": 100.0,
        "verdict": null,
        "percentile": null,
        "subs": []
      }
    ],
    "shotZones": {
      "restrictedArea": {
        "volume": 26.2,
        "efg": 63.6,
        "poss": 22
      },
      "paint": {
        "volume": 22.6,
        "efg": 52.6,
        "poss": 19
      },
      "midrange": {
        "volume": 10.7,
        "efg": 66.7,
        "poss": 9
      },
      "beyondArc": {
        "volume": 40.5,
        "efg": 66.2,
        "poss": 34
      }
    },
    "archetype": "Elite Three-Level Guard",
    "analysis": [
      "128.3 ORtg on 25.0% usage",
      "37.0% from 3 on 219 attempts and 85.7% from FT",
      "+2.3 FD/FC ratio, combined with his high FT% makes him both dangerous and comfortable at the line",
      "At least top 75th percentile in PPG for his 5 most frequent play types, ranging from .99 to 1.33 PPP"
    ]
  },
  "jennings": {
    "name": "Brandon Jennings",
    "number": 0,
    "position": "PG·SG",
    "primary_position": "PG",
    "year_abbr": "So",
    "year": "Sophomore",
    "height": "6-4",
    "weight": 175,
    "hometown": "Richmond, VA",
    "team": "VCU",
    "season": "2025-26",
    "games": 36,
    "kenpom": {
      "minPct": 61.8,
      "ortg": 114.6,
      "possPct": 18.1,
      "shotsPct": 16.6,
      "efg": 49.3,
      "ts": 57.2,
      "orPct": 4.0,
      "drPct": 12.1,
      "aRate": 15.2,
      "toRate": 17.2,
      "blkPct": 3.5,
      "stlPct": 3.9,
      "fc40": 4.8,
      "fd40": 3.9,
      "ftRate": 50.9,
      "ft": {
        "made": 94,
        "att": 110,
        "pct": 0.855
      },
      "twoP": {
        "made": 69,
        "att": 158,
        "pct": 0.437
      },
      "threeP": {
        "made": 25,
        "att": 58,
        "pct": 0.431
      }
    },
    "key": "jennings",
    "photo": "photos/jennings.png",
    "playTypes": [
      {
        "name": "Spot Up",
        "poss": 102,
        "timePct": 31.8,
        "pps": 0.922,
        "efg": 47.8,
        "verdict": "Average",
        "percentile": 47,
        "subs": [
          {
            "name": "No Dribble Jumper",
            "poss": 1,
            "timePct": 3.3,
            "pps": 0.0,
            "efg": 0.0
          },
          {
            "name": "Drives Right",
            "poss": 44,
            "timePct": 43.1,
            "pps": 0.727,
            "efg": 36.1
          },
          {
            "name": "Drives Left",
            "poss": 25,
            "timePct": 24.5,
            "pps": 0.68,
            "efg": 33.3
          },
          {
            "name": "Drives Straight",
            "poss": 1,
            "timePct": 1.0,
            "pps": 0.0,
            "efg": 0.0
          },
          {
            "name": "Turnover",
            "poss": 13,
            "timePct": 43.3,
            "pps": 0.0,
            "efg": null
          }
        ]
      },
      {
        "name": "Transition",
        "poss": 78,
        "timePct": 24.3,
        "pps": 1.077,
        "efg": 52.7,
        "verdict": "Average",
        "percentile": 50,
        "subs": [
          {
            "name": "Ballhandler",
            "poss": 35,
            "timePct": 44.9,
            "pps": 1.029,
            "efg": 45.5
          },
          {
            "name": "Right Wing",
            "poss": 18,
            "timePct": 23.1,
            "pps": 0.778,
            "efg": 40.0
          },
          {
            "name": "Left Wing",
            "poss": 12,
            "timePct": 15.4,
            "pps": 1.333,
            "efg": 62.5
          },
          {
            "name": "Trailer",
            "poss": 9,
            "timePct": 11.5,
            "pps": 1.333,
            "efg": 78.6
          },
          {
            "name": "Leak Outs",
            "poss": 2,
            "timePct": 2.6,
            "pps": 1.0,
            "efg": 50.0
          },
          {
            "name": "First Middle",
            "poss": 2,
            "timePct": 2.6,
            "pps": 2.0,
            "efg": 100.0
          }
        ]
      },
      {
        "name": "P&R Ball Handler",
        "poss": 51,
        "timePct": 15.9,
        "pps": 0.902,
        "efg": 47.1,
        "verdict": "Very Good",
        "percentile": 71,
        "subs": []
      },
      {
        "name": "Miscellaneous Plays",
        "poss": 30,
        "timePct": 9.3,
        "pps": 0.867,
        "efg": 75.0,
        "verdict": "Excellent",
        "percentile": 87,
        "subs": []
      },
      {
        "name": "Handoffs",
        "poss": 18,
        "timePct": 5.6,
        "pps": 0.778,
        "efg": 41.7,
        "verdict": "Average",
        "percentile": 37,
        "subs": []
      },
      {
        "name": "Offensive Rebounds (Put Backs)",
        "poss": 13,
        "timePct": 4.0,
        "pps": 1.077,
        "efg": 28.6,
        "verdict": "Average",
        "percentile": 40,
        "subs": []
      },
      {
        "name": "Isolation",
        "poss": 11,
        "timePct": 3.4,
        "pps": 1.273,
        "efg": 80.0,
        "verdict": "Excellent",
        "percentile": 97,
        "subs": []
      },
      {
        "name": "Post-Up",
        "poss": 7,
        "timePct": 2.2,
        "pps": 0.857,
        "efg": 50.0,
        "verdict": null,
        "percentile": null,
        "subs": []
      },
      {
        "name": "Cut",
        "poss": 5,
        "timePct": 1.6,
        "pps": 0.8,
        "efg": 50.0,
        "verdict": null,
        "percentile": null,
        "subs": []
      },
      {
        "name": "Off Screen",
        "poss": 4,
        "timePct": 1.2,
        "pps": 1.0,
        "efg": 50.0,
        "verdict": null,
        "percentile": null,
        "subs": []
      },
      {
        "name": "P&R Roll Man",
        "poss": 2,
        "timePct": 0.6,
        "pps": 0.0,
        "efg": 0.0,
        "verdict": null,
        "percentile": null,
        "subs": []
      }
    ],
    "shotTypes": [
      {
        "name": "Jump Shot",
        "poss": 66,
        "timePct": 30.3,
        "pps": 1.26,
        "efg": 62.9,
        "verdict": "Excellent",
        "percentile": 97,
        "subs": [
          {
            "name": "Catch and Shoot",
            "poss": 47,
            "timePct": 71.2,
            "pps": 1.28,
            "efg": 63.8,
            "subs": [
              {
                "name": "Guarded",
                "poss": 25,
                "timePct": 53.2,
                "pps": 1.32,
                "efg": 66.0
              },
              {
                "name": "Unguarded",
                "poss": 22,
                "timePct": 46.8,
                "pps": 1.23,
                "efg": 61.4
              }
            ]
          },
          {
            "name": "Dribble Jumper",
            "poss": 18,
            "timePct": 27.3,
            "pps": 1.28,
            "efg": 63.9,
            "subs": []
          },
          {
            "name": "Early Jumper",
            "poss": 0,
            "timePct": 0.0,
            "pps": null,
            "efg": null,
            "subs": []
          }
        ]
      },
      {
        "name": "At Rim",
        "poss": 116,
        "timePct": 53.2,
        "pps": 0.88,
        "efg": 44.0,
        "verdict": "Poor",
        "percentile": 10,
        "subs": [
          {
            "name": "Layup",
            "poss": 106,
            "timePct": 91.4,
            "pps": 0.83,
            "efg": 41.5,
            "subs": []
          },
          {
            "name": "Dunk",
            "poss": 7,
            "timePct": 6.0,
            "pps": 2.0,
            "efg": 100.0,
            "subs": []
          },
          {
            "name": "Tip",
            "poss": 3,
            "timePct": 2.6,
            "pps": 0.0,
            "efg": 0.0,
            "subs": []
          }
        ]
      },
      {
        "name": "Runner",
        "poss": 30,
        "timePct": 13.8,
        "pps": 0.67,
        "efg": 33.3,
        "verdict": "Average",
        "percentile": 33,
        "subs": []
      },
      {
        "name": "Hook",
        "poss": 7,
        "timePct": 3.2,
        "pps": 1.14,
        "efg": 57.1,
        "verdict": null,
        "percentile": null,
        "subs": []
      }
    ],
    "shotZones": {
      "restrictedArea": {
        "volume": 45.2,
        "efg": 39.5,
        "poss": 38
      },
      "paint": {
        "volume": 26.2,
        "efg": 40.9,
        "poss": 22
      },
      "midrange": {
        "volume": 0.0,
        "efg": null,
        "poss": 0
      },
      "beyondArc": {
        "volume": 28.6,
        "efg": 81.2,
        "poss": 24
      }
    },
    "archetype": "Two-Way Combo Guard",
    "analysis": [
      "43.1% from 3 on 58 attempts",
      "3.5 Blk%, 3.9 Stl%, great defensively for a guard",
      "50.9 FTRate and 85.5% FT"
    ]
  },
  "lewis": {
    "name": "Nyk Lewis",
    "number": 1,
    "position": "SG",
    "primary_position": "SG",
    "year_abbr": "Fr",
    "year": "Freshman",
    "height": "6-1",
    "weight": 195,
    "hometown": "Washington, DC",
    "team": "VCU",
    "season": "2025-26",
    "games": 35,
    "kenpom": {
      "minPct": 57.6,
      "ortg": 118.8,
      "possPct": 18.4,
      "shotsPct": 18.0,
      "efg": 51.4,
      "ts": 56.5,
      "orPct": 7.0,
      "drPct": 13.9,
      "aRate": 12.0,
      "toRate": 12.8,
      "blkPct": 0.1,
      "stlPct": 2.8,
      "fc40": 2.8,
      "fd40": 4.0,
      "ftRate": 49.1,
      "ft": {
        "made": 80,
        "att": 107,
        "pct": 0.748
      },
      "twoP": {
        "made": 43,
        "att": 91,
        "pct": 0.473
      },
      "threeP": {
        "made": 46,
        "att": 127,
        "pct": 0.362
      }
    },
    "key": "lewis",
    "photo": "photos/lewis.png",
    "playTypes": [
      {
        "name": "Spot Up",
        "poss": 111,
        "timePct": 36.9,
        "pps": 1.126,
        "efg": 56.4,
        "verdict": "Excellent",
        "percentile": 83,
        "subs": [
          {
            "name": "No Dribble Jumper",
            "poss": 1,
            "timePct": 3.8,
            "pps": 0.0,
            "efg": 0.0
          },
          {
            "name": "Drives Right",
            "poss": 10,
            "timePct": 9.0,
            "pps": 0.8,
            "efg": 16.7
          },
          {
            "name": "Drives Left",
            "poss": 25,
            "timePct": 22.5,
            "pps": 1.04,
            "efg": 55.3
          },
          {
            "name": "Drives Straight",
            "poss": 2,
            "timePct": 1.8,
            "pps": 1.0,
            "efg": 50.0
          },
          {
            "name": "Turnover",
            "poss": 8,
            "timePct": 30.8,
            "pps": 0.0,
            "efg": null
          }
        ]
      },
      {
        "name": "Transition",
        "poss": 55,
        "timePct": 18.3,
        "pps": 0.945,
        "efg": 50.0,
        "verdict": "Below Average",
        "percentile": 27,
        "subs": [
          {
            "name": "Ballhandler",
            "poss": 17,
            "timePct": 30.9,
            "pps": 0.471,
            "efg": 25.0
          },
          {
            "name": "Right Wing",
            "poss": 12,
            "timePct": 21.8,
            "pps": 1.0,
            "efg": 35.0
          },
          {
            "name": "Left Wing",
            "poss": 17,
            "timePct": 30.9,
            "pps": 1.0,
            "efg": 57.1
          },
          {
            "name": "Trailer",
            "poss": 2,
            "timePct": 3.6,
            "pps": 2.0,
            "efg": 150.0
          },
          {
            "name": "Leak Outs",
            "poss": 6,
            "timePct": 10.9,
            "pps": 1.5,
            "efg": 100.0
          },
          {
            "name": "First Middle",
            "poss": 1,
            "timePct": 1.8,
            "pps": 2.0,
            "efg": 100.0
          }
        ]
      },
      {
        "name": "P&R Ball Handler",
        "poss": 37,
        "timePct": 12.3,
        "pps": 0.73,
        "efg": 33.3,
        "verdict": "Average",
        "percentile": 38,
        "subs": []
      },
      {
        "name": "Offensive Rebounds (Put Backs)",
        "poss": 26,
        "timePct": 8.6,
        "pps": 1.038,
        "efg": 57.9,
        "verdict": "Average",
        "percentile": 33,
        "subs": []
      },
      {
        "name": "Miscellaneous Plays",
        "poss": 26,
        "timePct": 8.6,
        "pps": 0.962,
        "efg": 33.3,
        "verdict": "Excellent",
        "percentile": 92,
        "subs": []
      },
      {
        "name": "Isolation",
        "poss": 16,
        "timePct": 5.3,
        "pps": 1.188,
        "efg": 50.0,
        "verdict": "Excellent",
        "percentile": 93,
        "subs": []
      },
      {
        "name": "Handoffs",
        "poss": 14,
        "timePct": 4.7,
        "pps": 1.643,
        "efg": 79.2,
        "verdict": "Excellent",
        "percentile": 99,
        "subs": []
      },
      {
        "name": "Off Screen",
        "poss": 8,
        "timePct": 2.7,
        "pps": 0.25,
        "efg": 16.7,
        "verdict": null,
        "percentile": null,
        "subs": []
      },
      {
        "name": "Cut",
        "poss": 3,
        "timePct": 1.0,
        "pps": 1.0,
        "efg": 50.0,
        "verdict": null,
        "percentile": null,
        "subs": []
      },
      {
        "name": "Post-Up",
        "poss": 3,
        "timePct": 1.0,
        "pps": 0.0,
        "efg": 0.0,
        "verdict": null,
        "percentile": null,
        "subs": []
      },
      {
        "name": "P&R Roll Man",
        "poss": 2,
        "timePct": 0.7,
        "pps": 0.0,
        "efg": 0.0,
        "verdict": null,
        "percentile": null,
        "subs": []
      }
    ],
    "shotTypes": [
      {
        "name": "Jump Shot",
        "poss": 142,
        "timePct": 64.8,
        "pps": 1.03,
        "efg": 51.4,
        "verdict": "Very Good",
        "percentile": 71,
        "subs": [
          {
            "name": "Catch and Shoot",
            "poss": 104,
            "timePct": 73.2,
            "pps": 1.09,
            "efg": 54.3,
            "subs": [
              {
                "name": "Guarded",
                "poss": 50,
                "timePct": 48.1,
                "pps": 1.02,
                "efg": 51.0
              },
              {
                "name": "Unguarded",
                "poss": 54,
                "timePct": 51.9,
                "pps": 1.15,
                "efg": 57.4
              }
            ]
          },
          {
            "name": "Dribble Jumper",
            "poss": 36,
            "timePct": 25.4,
            "pps": 0.92,
            "efg": 45.8,
            "subs": []
          },
          {
            "name": "Early Jumper",
            "poss": 1,
            "timePct": 0.7,
            "pps": 3.0,
            "efg": 150.0,
            "subs": []
          }
        ]
      },
      {
        "name": "At Rim",
        "poss": 58,
        "timePct": 26.5,
        "pps": 1.14,
        "efg": 56.9,
        "verdict": "Average",
        "percentile": 47,
        "subs": [
          {
            "name": "Layup",
            "poss": 53,
            "timePct": 91.4,
            "pps": 1.17,
            "efg": 58.5,
            "subs": []
          },
          {
            "name": "Dunk",
            "poss": 0,
            "timePct": 0.0,
            "pps": null,
            "efg": null,
            "subs": []
          },
          {
            "name": "Tip",
            "poss": 5,
            "timePct": 8.6,
            "pps": 0.8,
            "efg": 40.0,
            "subs": []
          }
        ]
      },
      {
        "name": "Runner",
        "poss": 19,
        "timePct": 8.7,
        "pps": 0.63,
        "efg": 31.6,
        "verdict": "Below Average",
        "percentile": 28,
        "subs": []
      },
      {
        "name": "Hook",
        "poss": 1,
        "timePct": 0.5,
        "pps": 0.0,
        "efg": 0.0,
        "verdict": null,
        "percentile": null,
        "subs": []
      }
    ],
    "shotZones": {
      "restrictedArea": {
        "volume": 23.8,
        "efg": 63.3,
        "poss": 30
      },
      "paint": {
        "volume": 12.7,
        "efg": 31.2,
        "poss": 16
      },
      "midrange": {
        "volume": 2.4,
        "efg": 33.3,
        "poss": 3
      },
      "beyondArc": {
        "volume": 61.1,
        "efg": 46.8,
        "poss": 77
      }
    },
    "archetype": "Standout Freshman Combo Guard",
    "analysis": [
      "118.8 ORtg on 18.4% usage as a freshman is well above average for his role",
      "36.2% from 3 on 127 attempts and 1.126 PPS Spot Up (Excellent), however numbers not competing with veteran shooters on roster",
      "+3.1 FD/FC ratio, with an average of 6 fouls per 40 mins"
    ]
  },
  "belle": {
    "name": "Michael Belle",
    "number": 8,
    "position": "PF",
    "primary_position": "PF",
    "year_abbr": "Jr",
    "year": "Junior",
    "height": "6-8",
    "weight": 220,
    "hometown": "London, England",
    "team": "VCU",
    "season": "2025-26",
    "games": 36,
    "kenpom": {
      "minPct": 55.7,
      "ortg": 115.0,
      "possPct": 16.2,
      "shotsPct": 16.5,
      "efg": 59.3,
      "ts": 58.4,
      "orPct": 7.4,
      "drPct": 17.4,
      "aRate": 8.8,
      "toRate": 15.0,
      "blkPct": 3.5,
      "stlPct": 1.6,
      "fc40": 3.9,
      "fd40": 2.9,
      "ftRate": 33.0,
      "ft": {
        "made": 32,
        "att": 64,
        "pct": 0.5
      },
      "twoP": {
        "made": 85,
        "att": 154,
        "pct": 0.552
      },
      "threeP": {
        "made": 20,
        "att": 40,
        "pct": 0.5
      }
    },
    "key": "belle",
    "photo": "photos/belle.png",
    "playTypes": [
      {
        "name": "Spot Up",
        "poss": 72,
        "timePct": 27.9,
        "pps": 1.0,
        "efg": 60.5,
        "verdict": "Good",
        "percentile": 64,
        "subs": [
          {
            "name": "No Dribble Jumper",
            "poss": 27,
            "timePct": 37.5,
            "pps": 1.333,
            "efg": 66.7
          },
          {
            "name": "Drives Right",
            "poss": 24,
            "timePct": 33.3,
            "pps": 0.417,
            "efg": 30.8
          },
          {
            "name": "Drives Left",
            "poss": 21,
            "timePct": 29.2,
            "pps": 1.238,
            "efg": 73.5
          },
          {
            "name": "Turnover",
            "poss": 8,
            "timePct": 50.0,
            "pps": 0.0,
            "efg": null
          }
        ]
      },
      {
        "name": "Cut",
        "poss": 51,
        "timePct": 19.8,
        "pps": 1.098,
        "efg": 63.9,
        "verdict": "Average",
        "percentile": 33,
        "subs": []
      },
      {
        "name": "Offensive Rebounds (Put Backs)",
        "poss": 34,
        "timePct": 13.2,
        "pps": 1.029,
        "efg": 53.6,
        "verdict": "Average",
        "percentile": 32,
        "subs": []
      },
      {
        "name": "Transition",
        "poss": 32,
        "timePct": 12.4,
        "pps": 1.031,
        "efg": 55.6,
        "verdict": "Average",
        "percentile": 41,
        "subs": [
          {
            "name": "Ballhandler",
            "poss": 6,
            "timePct": 18.8,
            "pps": 0.667,
            "efg": 40.0
          },
          {
            "name": "Right Wing",
            "poss": 6,
            "timePct": 18.8,
            "pps": 1.0,
            "efg": 60.0
          },
          {
            "name": "Left Wing",
            "poss": 8,
            "timePct": 25.0,
            "pps": 0.75,
            "efg": 37.5
          },
          {
            "name": "Leak Outs",
            "poss": 4,
            "timePct": 12.5,
            "pps": 1.25,
            "efg": 66.7
          },
          {
            "name": "First Middle",
            "poss": 8,
            "timePct": 25.0,
            "pps": 1.5,
            "efg": 83.3
          }
        ]
      },
      {
        "name": "P&R Roll Man",
        "poss": 18,
        "timePct": 7.0,
        "pps": 1.222,
        "efg": 64.7,
        "verdict": "Very Good",
        "percentile": 75,
        "subs": []
      },
      {
        "name": "Miscellaneous Plays",
        "poss": 16,
        "timePct": 6.2,
        "pps": 0.625,
        "efg": 66.7,
        "verdict": "Good",
        "percentile": 63,
        "subs": []
      },
      {
        "name": "P&R Ball Handler",
        "poss": 14,
        "timePct": 5.4,
        "pps": 1.071,
        "efg": 75.0,
        "verdict": "Excellent",
        "percentile": 93,
        "subs": []
      },
      {
        "name": "Handoffs",
        "poss": 9,
        "timePct": 3.5,
        "pps": 0.889,
        "efg": 50.0,
        "verdict": null,
        "percentile": null,
        "subs": []
      },
      {
        "name": "Post-Up",
        "poss": 5,
        "timePct": 1.9,
        "pps": 1.2,
        "efg": 50.0,
        "verdict": null,
        "percentile": null,
        "subs": []
      },
      {
        "name": "Isolation",
        "poss": 4,
        "timePct": 1.6,
        "pps": 0.25,
        "efg": 0.0,
        "verdict": null,
        "percentile": null,
        "subs": []
      },
      {
        "name": "Off Screen",
        "poss": 3,
        "timePct": 1.2,
        "pps": 1.333,
        "efg": 75.0,
        "verdict": null,
        "percentile": null,
        "subs": []
      }
    ],
    "shotTypes": [
      {
        "name": "Jump Shot",
        "poss": 48,
        "timePct": 24.7,
        "pps": 1.33,
        "efg": 66.7,
        "verdict": "Excellent",
        "percentile": 99,
        "subs": [
          {
            "name": "Catch and Shoot",
            "poss": 36,
            "timePct": 75.0,
            "pps": 1.33,
            "efg": 66.7,
            "subs": [
              {
                "name": "Guarded",
                "poss": 12,
                "timePct": 33.3,
                "pps": 1.5,
                "efg": 75.0
              },
              {
                "name": "Unguarded",
                "poss": 24,
                "timePct": 66.7,
                "pps": 1.25,
                "efg": 62.5
              }
            ]
          },
          {
            "name": "Dribble Jumper",
            "poss": 10,
            "timePct": 20.8,
            "pps": 1.6,
            "efg": 80.0,
            "subs": []
          },
          {
            "name": "Early Jumper",
            "poss": 0,
            "timePct": 0.0,
            "pps": null,
            "efg": null,
            "subs": []
          }
        ]
      },
      {
        "name": "At Rim",
        "poss": 108,
        "timePct": 55.7,
        "pps": 1.2,
        "efg": 60.2,
        "verdict": "Good",
        "percentile": 61,
        "subs": [
          {
            "name": "Layup",
            "poss": 85,
            "timePct": 78.7,
            "pps": 1.27,
            "efg": 63.5,
            "subs": []
          },
          {
            "name": "Dunk",
            "poss": 15,
            "timePct": 13.9,
            "pps": 1.2,
            "efg": 60.0,
            "subs": []
          },
          {
            "name": "Tip",
            "poss": 8,
            "timePct": 7.4,
            "pps": 0.5,
            "efg": 25.0,
            "subs": []
          }
        ]
      },
      {
        "name": "Runner",
        "poss": 30,
        "timePct": 15.5,
        "pps": 0.93,
        "efg": 46.7,
        "verdict": "Very Good",
        "percentile": 73,
        "subs": []
      },
      {
        "name": "Hook",
        "poss": 8,
        "timePct": 4.1,
        "pps": 1.0,
        "efg": 50.0,
        "verdict": null,
        "percentile": null,
        "subs": []
      }
    ],
    "shotZones": {
      "restrictedArea": {
        "volume": 57.1,
        "efg": 60.4,
        "poss": 48
      },
      "paint": {
        "volume": 26.2,
        "efg": 18.2,
        "poss": 22
      },
      "midrange": {
        "volume": 0.0,
        "efg": null,
        "poss": 0
      },
      "beyondArc": {
        "volume": 16.7,
        "efg": 64.3,
        "poss": 14
      }
    },
    "archetype": "Efficient Stretch 4 / Elite Rebounder",
    "analysis": [
      "17.4 DR% and 7.4 OR% make him the team's best per-minute rebounder",
      "50.0% from 3 on 40 attempts (notably small sample but elite efficiency)"
    ]
  },
  "tracey": {
    "name": "Jadrian Tracey",
    "number": 2,
    "position": "SF",
    "primary_position": "SF",
    "year_abbr": "Sr",
    "year": "Senior",
    "height": "6-6",
    "weight": 210,
    "hometown": "Fort Myers, FL",
    "team": "VCU",
    "season": "2025-26",
    "games": 36,
    "kenpom": {
      "minPct": 53.9,
      "ortg": 102.9,
      "possPct": 23.8,
      "shotsPct": 25.3,
      "efg": 51.9,
      "ts": 54.0,
      "orPct": 3.8,
      "drPct": 10.6,
      "aRate": 15.7,
      "toRate": 19.7,
      "blkPct": 1.7,
      "stlPct": 2.1,
      "fc40": 4.2,
      "fd40": 3.2,
      "ftRate": 23.3,
      "ft": {
        "made": 46,
        "att": 67,
        "pct": 0.687
      },
      "twoP": {
        "made": 56,
        "att": 115,
        "pct": 0.487
      },
      "threeP": {
        "made": 62,
        "att": 172,
        "pct": 0.36
      }
    },
    "key": "tracey",
    "photo": "photos/tracey.png",
    "playTypes": [
      {
        "name": "Spot Up",
        "poss": 134,
        "timePct": 35.4,
        "pps": 1.112,
        "efg": 58.7,
        "verdict": "Very Good",
        "percentile": 82,
        "subs": [
          {
            "name": "No Dribble Jumper",
            "poss": 1,
            "timePct": 3.6,
            "pps": 0.0,
            "efg": 0.0
          },
          {
            "name": "Drives Right",
            "poss": 12,
            "timePct": 9.0,
            "pps": 0.75,
            "efg": 25.0
          },
          {
            "name": "Drives Left",
            "poss": 23,
            "timePct": 17.2,
            "pps": 0.87,
            "efg": 50.0
          },
          {
            "name": "Drives Straight",
            "poss": 3,
            "timePct": 2.2,
            "pps": 1.0,
            "efg": 50.0
          },
          {
            "name": "Turnover",
            "poss": 23,
            "timePct": 82.1,
            "pps": 0.0,
            "efg": null
          }
        ]
      },
      {
        "name": "Transition",
        "poss": 78,
        "timePct": 20.6,
        "pps": 0.859,
        "efg": 49.1,
        "verdict": "Below Average",
        "percentile": 17,
        "subs": [
          {
            "name": "Ballhandler",
            "poss": 26,
            "timePct": 33.3,
            "pps": 0.462,
            "efg": 31.8
          },
          {
            "name": "Right Wing",
            "poss": 19,
            "timePct": 24.4,
            "pps": 0.789,
            "efg": 38.9
          },
          {
            "name": "Left Wing",
            "poss": 18,
            "timePct": 23.1,
            "pps": 1.333,
            "efg": 62.5
          },
          {
            "name": "Trailer",
            "poss": 8,
            "timePct": 10.3,
            "pps": 1.0,
            "efg": 50.0
          },
          {
            "name": "Leak Outs",
            "poss": 3,
            "timePct": 3.8,
            "pps": 2.0,
            "efg": 100.0
          },
          {
            "name": "First Middle",
            "poss": 3,
            "timePct": 3.8,
            "pps": 0.667,
            "efg": 50.0
          }
        ]
      },
      {
        "name": "P&R Ball Handler",
        "poss": 37,
        "timePct": 9.8,
        "pps": 1.0,
        "efg": 60.7,
        "verdict": "Excellent",
        "percentile": 87,
        "subs": []
      },
      {
        "name": "Miscellaneous Plays",
        "poss": 28,
        "timePct": 7.4,
        "pps": 0.179,
        "efg": 50.0,
        "verdict": "Poor",
        "percentile": 8,
        "subs": []
      },
      {
        "name": "Handoffs",
        "poss": 24,
        "timePct": 6.3,
        "pps": 0.958,
        "efg": 50.0,
        "verdict": "Good",
        "percentile": 65,
        "subs": []
      },
      {
        "name": "Isolation",
        "poss": 18,
        "timePct": 4.8,
        "pps": 0.5,
        "efg": 30.0,
        "verdict": "Poor",
        "percentile": 12,
        "subs": []
      },
      {
        "name": "Off Screen",
        "poss": 17,
        "timePct": 4.5,
        "pps": 0.588,
        "efg": 33.3,
        "verdict": "Poor",
        "percentile": 10,
        "subs": []
      },
      {
        "name": "Post-Up",
        "poss": 16,
        "timePct": 4.2,
        "pps": 0.813,
        "efg": 46.2,
        "verdict": "Average",
        "percentile": 37,
        "subs": []
      },
      {
        "name": "Offensive Rebounds (Put Backs)",
        "poss": 15,
        "timePct": 4.0,
        "pps": 0.933,
        "efg": 36.4,
        "verdict": "Below Average",
        "percentile": 21,
        "subs": []
      },
      {
        "name": "Cut",
        "poss": 10,
        "timePct": 2.6,
        "pps": 1.1,
        "efg": 55.6,
        "verdict": "Average",
        "percentile": 34,
        "subs": []
      },
      {
        "name": "P&R Roll Man",
        "poss": 1,
        "timePct": 0.3,
        "pps": 2.0,
        "efg": null,
        "verdict": null,
        "percentile": null,
        "subs": []
      }
    ],
    "shotTypes": [
      {
        "name": "Jump Shot",
        "poss": 185,
        "timePct": 64.5,
        "pps": 1.07,
        "efg": 53.5,
        "verdict": "Very Good",
        "percentile": 79,
        "subs": [
          {
            "name": "Catch and Shoot",
            "poss": 135,
            "timePct": 73.0,
            "pps": 1.09,
            "efg": 54.4,
            "subs": [
              {
                "name": "Guarded",
                "poss": 86,
                "timePct": 63.7,
                "pps": 1.01,
                "efg": 50.6
              },
              {
                "name": "Unguarded",
                "poss": 49,
                "timePct": 36.3,
                "pps": 1.22,
                "efg": 61.2
              }
            ]
          },
          {
            "name": "Dribble Jumper",
            "poss": 50,
            "timePct": 27.0,
            "pps": 1.02,
            "efg": 51.0,
            "subs": []
          },
          {
            "name": "Early Jumper",
            "poss": 11,
            "timePct": 5.9,
            "pps": 0.64,
            "efg": 31.8,
            "subs": []
          }
        ]
      },
      {
        "name": "At Rim",
        "poss": 88,
        "timePct": 30.7,
        "pps": 1.02,
        "efg": 51.1,
        "verdict": "Below Average",
        "percentile": 26,
        "subs": [
          {
            "name": "Layup",
            "poss": 77,
            "timePct": 87.5,
            "pps": 1.01,
            "efg": 50.6,
            "subs": []
          },
          {
            "name": "Dunk",
            "poss": 10,
            "timePct": 11.4,
            "pps": 1.0,
            "efg": 50.0,
            "subs": []
          },
          {
            "name": "Tip",
            "poss": 1,
            "timePct": 1.1,
            "pps": 2.0,
            "efg": 100.0,
            "subs": []
          }
        ]
      },
      {
        "name": "Runner",
        "poss": 4,
        "timePct": 1.4,
        "pps": 0.5,
        "efg": 25.0,
        "verdict": null,
        "percentile": null,
        "subs": []
      },
      {
        "name": "Hook",
        "poss": 8,
        "timePct": 2.8,
        "pps": 0.75,
        "efg": 37.5,
        "verdict": null,
        "percentile": null,
        "subs": []
      }
    ],
    "shotZones": {
      "restrictedArea": {
        "volume": 31.0,
        "efg": 61.5,
        "poss": 26
      },
      "paint": {
        "volume": 8.3,
        "efg": 14.3,
        "poss": 7
      },
      "midrange": {
        "volume": 2.4,
        "efg": 100.0,
        "poss": 2
      },
      "beyondArc": {
        "volume": 58.3,
        "efg": 42.9,
        "poss": 49
      }
    },
    "archetype": "High-Volume Wing",
    "analysis": [
      "Spot Up and P&R Ball Handler (1st and 3rd most frequent plays) his strongest, but ranks below average in transition his 2nd most frequent (17th percentile, 20% of plays)",
      "19.7 TORate is the highest among rotation players, ball security is the concern"
    ]
  },
  "ward": {
    "name": "Tyrell Ward",
    "number": 15,
    "position": "SF",
    "primary_position": "SF",
    "year_abbr": "Jr",
    "year": "Junior",
    "height": "6-6",
    "weight": 195,
    "hometown": "Washington, DC",
    "team": "VCU",
    "season": "2025-26",
    "games": 31,
    "kenpom": {
      "minPct": 29.3,
      "ortg": 103.5,
      "possPct": 21.8,
      "shotsPct": 21.9,
      "efg": 52.2,
      "ts": 54.8,
      "orPct": 6.0,
      "drPct": 11.7,
      "aRate": 6.8,
      "toRate": 17.5,
      "blkPct": 2.0,
      "stlPct": 2.3,
      "fc40": 2.5,
      "fd40": 4.3,
      "ftRate": 43.0,
      "ft": {
        "made": 37,
        "att": 58,
        "pct": 0.638
      },
      "twoP": {
        "made": 42,
        "att": 73,
        "pct": 0.575
      },
      "threeP": {
        "made": 19,
        "att": 62,
        "pct": 0.306
      }
    },
    "key": "ward",
    "photo": "photos/ward.png",
    "playTypes": [
      {
        "name": "Spot Up",
        "poss": 62,
        "timePct": 32.3,
        "pps": 0.984,
        "efg": 48.2,
        "verdict": "Good",
        "percentile": 59,
        "subs": [
          {
            "name": "No Dribble Jumper",
            "poss": 43,
            "timePct": 69.4,
            "pps": 1.0,
            "efg": 48.8
          },
          {
            "name": "Drives Right",
            "poss": 11,
            "timePct": 17.7,
            "pps": 0.909,
            "efg": 50.0
          },
          {
            "name": "Drives Left",
            "poss": 6,
            "timePct": 9.7,
            "pps": 1.0,
            "efg": 33.3
          },
          {
            "name": "Drives Straight",
            "poss": 2,
            "timePct": 3.2,
            "pps": 1.0,
            "efg": 50.0
          },
          {
            "name": "Turnover",
            "poss": 7,
            "timePct": 46.7,
            "pps": 0.0,
            "efg": null
          }
        ]
      },
      {
        "name": "Transition",
        "poss": 51,
        "timePct": 26.6,
        "pps": 0.961,
        "efg": 52.9,
        "verdict": "Below Average",
        "percentile": 29,
        "subs": [
          {
            "name": "Ballhandler",
            "poss": 13,
            "timePct": 25.5,
            "pps": 1.154,
            "efg": 78.6
          },
          {
            "name": "Right Wing",
            "poss": 13,
            "timePct": 25.5,
            "pps": 0.462,
            "efg": 12.5
          },
          {
            "name": "Left Wing",
            "poss": 16,
            "timePct": 31.4,
            "pps": 1.125,
            "efg": 62.5
          },
          {
            "name": "Trailer",
            "poss": 6,
            "timePct": 11.8,
            "pps": 0.833,
            "efg": 41.7
          },
          {
            "name": "Leak Outs",
            "poss": 2,
            "timePct": 3.9,
            "pps": 1.5,
            "efg": 100.0
          },
          {
            "name": "First Middle",
            "poss": 1,
            "timePct": 2.0,
            "pps": 2.0,
            "efg": 100.0
          }
        ]
      },
      {
        "name": "Cut",
        "poss": 27,
        "timePct": 14.1,
        "pps": 1.444,
        "efg": 78.9,
        "verdict": "Excellent",
        "percentile": 84,
        "subs": []
      },
      {
        "name": "Miscellaneous Plays",
        "poss": 15,
        "timePct": 7.8,
        "pps": 0.533,
        "efg": 50.0,
        "verdict": "Average",
        "percentile": 50,
        "subs": []
      },
      {
        "name": "Offensive Rebounds (Put Backs)",
        "poss": 12,
        "timePct": 6.3,
        "pps": 0.917,
        "efg": 37.5,
        "verdict": "Below Average",
        "percentile": 18,
        "subs": []
      },
      {
        "name": "P&R Ball Handler",
        "poss": 8,
        "timePct": 4.2,
        "pps": 0.5,
        "efg": 33.3,
        "verdict": null,
        "percentile": null,
        "subs": []
      },
      {
        "name": "Handoffs",
        "poss": 8,
        "timePct": 4.2,
        "pps": 0.0,
        "efg": 0.0,
        "verdict": null,
        "percentile": null,
        "subs": []
      },
      {
        "name": "Isolation",
        "poss": 3,
        "timePct": 1.6,
        "pps": 1.0,
        "efg": 50.0,
        "verdict": null,
        "percentile": null,
        "subs": []
      },
      {
        "name": "Off Screen",
        "poss": 3,
        "timePct": 1.6,
        "pps": 0.0,
        "efg": 0.0,
        "verdict": null,
        "percentile": null,
        "subs": []
      },
      {
        "name": "P&R Roll Man",
        "poss": 2,
        "timePct": 1.0,
        "pps": 1.5,
        "efg": 75.0,
        "verdict": null,
        "percentile": null,
        "subs": []
      },
      {
        "name": "Post-Up",
        "poss": 1,
        "timePct": 0.5,
        "pps": 2.0,
        "efg": null,
        "verdict": null,
        "percentile": null,
        "subs": []
      }
    ],
    "shotTypes": [
      {
        "name": "Jump Shot",
        "poss": 65,
        "timePct": 47.4,
        "pps": 0.91,
        "efg": 45.4,
        "verdict": "Average",
        "percentile": 44,
        "subs": [
          {
            "name": "Catch and Shoot",
            "poss": 58,
            "timePct": 89.2,
            "pps": 0.88,
            "efg": 44.0,
            "subs": [
              {
                "name": "Guarded",
                "poss": 28,
                "timePct": 48.3,
                "pps": 0.86,
                "efg": 42.9
              },
              {
                "name": "Unguarded",
                "poss": 30,
                "timePct": 51.7,
                "pps": 0.9,
                "efg": 45.0
              }
            ]
          },
          {
            "name": "Dribble Jumper",
            "poss": 7,
            "timePct": 10.8,
            "pps": 1.14,
            "efg": 57.1,
            "subs": []
          },
          {
            "name": "Early Jumper",
            "poss": 1,
            "timePct": 1.5,
            "pps": 3.0,
            "efg": 150.0,
            "subs": []
          }
        ]
      },
      {
        "name": "At Rim",
        "poss": 68,
        "timePct": 49.6,
        "pps": 1.12,
        "efg": 55.9,
        "verdict": "Average",
        "percentile": 43,
        "subs": [
          {
            "name": "Layup",
            "poss": 50,
            "timePct": 73.5,
            "pps": 0.96,
            "efg": 48.0,
            "subs": []
          },
          {
            "name": "Dunk",
            "poss": 14,
            "timePct": 20.6,
            "pps": 1.57,
            "efg": 78.6,
            "subs": []
          },
          {
            "name": "Tip",
            "poss": 4,
            "timePct": 5.9,
            "pps": 1.5,
            "efg": 75.0,
            "subs": []
          }
        ]
      },
      {
        "name": "Runner",
        "poss": 4,
        "timePct": 2.9,
        "pps": 1.5,
        "efg": 75.0,
        "verdict": null,
        "percentile": null,
        "subs": []
      },
      {
        "name": "Hook",
        "poss": 0,
        "timePct": 0.0,
        "pps": null,
        "efg": null,
        "verdict": null,
        "percentile": null,
        "subs": []
      }
    ],
    "shotZones": {
      "restrictedArea": {
        "volume": 47.6,
        "efg": 60.0,
        "poss": 40
      },
      "paint": {
        "volume": 11.9,
        "efg": 60.0,
        "poss": 10
      },
      "midrange": {
        "volume": 0.0,
        "efg": null,
        "poss": 0
      },
      "beyondArc": {
        "volume": 40.5,
        "efg": 48.5,
        "poss": 34
      }
    },
    "archetype": "Aggressive Wing",
    "analysis": [
      "57.5% on 2s vs 30.6% from 3 primarily shooting outside the rim",
      "43.0 FTRate paired with 21.8% usage, drives looking for contact",
      "1.444 PPS on Cuts (Excellent) on 27 poss, efficient off-ball mover"
    ]
  },
  "ahmad": {
    "name": "Ahmad Nowell",
    "number": 4,
    "position": "SG",
    "primary_position": "SG",
    "year_abbr": "So",
    "year": "Sophomore",
    "height": "6-0",
    "weight": 195,
    "hometown": "Philadelphia, PA",
    "team": "VCU",
    "season": "2025-26",
    "games": 28,
    "kenpom": {
      "minPct": 20.2,
      "ortg": 119.7,
      "possPct": 18.9,
      "shotsPct": 20.0,
      "efg": 58.8,
      "ts": 62.2,
      "orPct": 2.4,
      "drPct": 10.2,
      "aRate": 10.9,
      "toRate": 14.6,
      "blkPct": 0.7,
      "stlPct": 2.8,
      "fc40": 5.2,
      "fd40": 3.9,
      "ftRate": 42.4,
      "ft": {
        "made": 27,
        "att": 36,
        "pct": 0.75
      },
      "twoP": {
        "made": 14,
        "att": 27,
        "pct": 0.519
      },
      "threeP": {
        "made": 24,
        "att": 58,
        "pct": 0.414
      }
    },
    "key": "ahmad",
    "photo": "photos/ahmad.png",
    "playTypes": [
      {
        "name": "Spot Up",
        "poss": 40,
        "timePct": 33.9,
        "pps": 1.4,
        "efg": 73.0,
        "verdict": "Excellent",
        "percentile": 99,
        "subs": [
          {
            "name": "No Dribble Jumper",
            "poss": 1,
            "timePct": 9.1,
            "pps": 0.0,
            "efg": 0.0
          },
          {
            "name": "Drives Right",
            "poss": 4,
            "timePct": 10.0,
            "pps": 1.5,
            "efg": 66.7
          },
          {
            "name": "Drives Left",
            "poss": 6,
            "timePct": 15.0,
            "pps": 0.833,
            "efg": 62.5
          },
          {
            "name": "Turnover",
            "poss": 2,
            "timePct": 18.2,
            "pps": 0.0,
            "efg": null
          }
        ]
      },
      {
        "name": "Transition",
        "poss": 27,
        "timePct": 22.9,
        "pps": 0.778,
        "efg": 41.7,
        "verdict": "Poor",
        "percentile": 11,
        "subs": [
          {
            "name": "Ballhandler",
            "poss": 9,
            "timePct": 33.3,
            "pps": 0.667,
            "efg": 50.0
          },
          {
            "name": "Right Wing",
            "poss": 12,
            "timePct": 44.4,
            "pps": 1.083,
            "efg": 56.3
          },
          {
            "name": "Left Wing",
            "poss": 2,
            "timePct": 7.4,
            "pps": 0.0,
            "efg": 0.0
          },
          {
            "name": "Trailer",
            "poss": 2,
            "timePct": 7.4,
            "pps": 0.0,
            "efg": 0.0
          },
          {
            "name": "Leak Outs",
            "poss": 1,
            "timePct": 3.7,
            "pps": 2.0,
            "efg": 100.0
          },
          {
            "name": "First Middle",
            "poss": 1,
            "timePct": 3.7,
            "pps": 0.0,
            "efg": 0.0
          }
        ]
      },
      {
        "name": "P&R Ball Handler",
        "poss": 17,
        "timePct": 14.4,
        "pps": 1.059,
        "efg": 50.0,
        "verdict": "Excellent",
        "percentile": 91,
        "subs": []
      },
      {
        "name": "Miscellaneous Plays",
        "poss": 11,
        "timePct": 9.3,
        "pps": 1.091,
        "efg": 50.0,
        "verdict": "Excellent",
        "percentile": 97,
        "subs": []
      },
      {
        "name": "Handoffs",
        "poss": 8,
        "timePct": 6.8,
        "pps": 0.5,
        "efg": 25.0,
        "verdict": null,
        "percentile": null,
        "subs": []
      },
      {
        "name": "Isolation",
        "poss": 6,
        "timePct": 5.1,
        "pps": 0.5,
        "efg": 50.0,
        "verdict": null,
        "percentile": null,
        "subs": []
      },
      {
        "name": "Offensive Rebounds (Put Backs)",
        "poss": 3,
        "timePct": 2.5,
        "pps": 2.0,
        "efg": 150.0,
        "verdict": null,
        "percentile": null,
        "subs": []
      },
      {
        "name": "Off Screen",
        "poss": 3,
        "timePct": 2.5,
        "pps": 0.667,
        "efg": 33.3,
        "verdict": null,
        "percentile": null,
        "subs": []
      },
      {
        "name": "P&R Roll Man",
        "poss": 2,
        "timePct": 1.7,
        "pps": 1.5,
        "efg": 75.0,
        "verdict": null,
        "percentile": null,
        "subs": []
      },
      {
        "name": "Cut",
        "poss": 1,
        "timePct": 0.8,
        "pps": 2.0,
        "efg": 100.0,
        "verdict": null,
        "percentile": null,
        "subs": []
      },
      {
        "name": "Post-Up",
        "poss": 0,
        "timePct": 0.0,
        "pps": null,
        "efg": null,
        "verdict": null,
        "percentile": null,
        "subs": []
      }
    ],
    "shotTypes": [
      {
        "name": "Jump Shot",
        "poss": 62,
        "timePct": 72.1,
        "pps": 1.19,
        "efg": 59.7,
        "verdict": "Excellent",
        "percentile": 94,
        "subs": [
          {
            "name": "Catch and Shoot",
            "poss": 47,
            "timePct": 75.8,
            "pps": 1.21,
            "efg": 60.6,
            "subs": [
              {
                "name": "Guarded",
                "poss": 32,
                "timePct": 68.1,
                "pps": 1.31,
                "efg": 65.6
              },
              {
                "name": "Unguarded",
                "poss": 15,
                "timePct": 31.9,
                "pps": 1.0,
                "efg": 50.0
              }
            ]
          },
          {
            "name": "Dribble Jumper",
            "poss": 14,
            "timePct": 22.6,
            "pps": 1.0,
            "efg": 50.0,
            "subs": []
          },
          {
            "name": "Early Jumper",
            "poss": 0,
            "timePct": 0.0,
            "pps": null,
            "efg": null,
            "subs": []
          }
        ]
      },
      {
        "name": "At Rim",
        "poss": 23,
        "timePct": 26.7,
        "pps": 1.13,
        "efg": 56.5,
        "verdict": "Average",
        "percentile": 46,
        "subs": [
          {
            "name": "Layup",
            "poss": 23,
            "timePct": 100.0,
            "pps": 1.13,
            "efg": 56.5,
            "subs": []
          },
          {
            "name": "Dunk",
            "poss": 0,
            "timePct": 0.0,
            "pps": null,
            "efg": null,
            "subs": []
          },
          {
            "name": "Tip",
            "poss": 0,
            "timePct": 0.0,
            "pps": null,
            "efg": null,
            "subs": []
          }
        ]
      },
      {
        "name": "Runner",
        "poss": 1,
        "timePct": 1.2,
        "pps": 0.0,
        "efg": 0.0,
        "verdict": null,
        "percentile": null,
        "subs": []
      },
      {
        "name": "Hook",
        "poss": 0,
        "timePct": 0.0,
        "pps": null,
        "efg": null,
        "verdict": null,
        "percentile": null,
        "subs": []
      }
    ],
    "shotZones": {
      "restrictedArea": {
        "volume": 26.2,
        "efg": 59.1,
        "poss": 22
      },
      "paint": {
        "volume": 2.4,
        "efg": 0.0,
        "poss": 2
      },
      "midrange": {
        "volume": 3.6,
        "efg": 33.3,
        "poss": 3
      },
      "beyondArc": {
        "volume": 67.9,
        "efg": 63.2,
        "poss": 57
      }
    },
    "archetype": "Spark Spot-Up Specialist",
    "analysis": [
      "11th percentile in transition",
      "41.4% from 3 on 58 attempts and 1.4 PPS Spot Up (99th percentile, his most frequent look)",
      "119.7 ORtg on 18.9% usage in limited minutes",
      "Small sample (20% min)"
    ]
  },
  "mitchell": {
    "name": "Keyshawn Mitchell",
    "number": 22,
    "position": "C",
    "primary_position": "C",
    "year_abbr": "Jr",
    "year": "Junior",
    "height": "6-11",
    "weight": 215,
    "hometown": "Brooklyn, NY",
    "team": "VCU",
    "season": "2025-26",
    "games": 20,
    "kenpom": {
      "minPct": 14.6,
      "ortg": 105.9,
      "possPct": 17.5,
      "shotsPct": 15.3,
      "efg": 45.7,
      "ts": 50.7,
      "orPct": 7.1,
      "drPct": 20.9,
      "aRate": 8.2,
      "toRate": 14.1,
      "blkPct": 2.5,
      "stlPct": 1.1,
      "fc40": 4.5,
      "fd40": 4.7,
      "ftRate": 72.3,
      "ft": {
        "made": 21,
        "att": 34,
        "pct": 0.618
      },
      "twoP": {
        "made": 14,
        "att": 23,
        "pct": 0.609
      },
      "threeP": {
        "made": 5,
        "att": 24,
        "pct": 0.208
      }
    },
    "key": "mitchell",
    "photo": "photos/mitchell.png",
    "playTypes": [
      {
        "name": "Spot Up",
        "poss": 18,
        "timePct": 25.7,
        "pps": 0.5,
        "efg": 25.0,
        "verdict": "Poor",
        "percentile": 5,
        "subs": [
          {
            "name": "No Dribble Jumper",
            "poss": 17,
            "timePct": 94.4,
            "pps": 0.529,
            "efg": 26.5
          },
          {
            "name": "Drives Left",
            "poss": 1,
            "timePct": 5.6,
            "pps": 0.0,
            "efg": 0.0
          },
          {
            "name": "Turnover",
            "poss": 2,
            "timePct": 50.0,
            "pps": 0.0,
            "efg": null
          }
        ]
      },
      {
        "name": "Cut",
        "poss": 17,
        "timePct": 24.3,
        "pps": 1.471,
        "efg": 72.7,
        "verdict": "Excellent",
        "percentile": 87,
        "subs": []
      },
      {
        "name": "Transition",
        "poss": 10,
        "timePct": 14.3,
        "pps": 1.0,
        "efg": 70.0,
        "verdict": "Average",
        "percentile": 38,
        "subs": [
          {
            "name": "Right Wing",
            "poss": 1,
            "timePct": 10.0,
            "pps": 0.0,
            "efg": 0.0
          },
          {
            "name": "Left Wing",
            "poss": 5,
            "timePct": 50.0,
            "pps": 1.8,
            "efg": 87.5
          },
          {
            "name": "Trailer",
            "poss": 1,
            "timePct": 10.0,
            "pps": 0.0,
            "efg": null
          },
          {
            "name": "First Middle",
            "poss": 3,
            "timePct": 30.0,
            "pps": 0.333,
            "efg": null
          }
        ]
      },
      {
        "name": "P&R Roll Man",
        "poss": 8,
        "timePct": 11.4,
        "pps": 1.125,
        "efg": 60.0,
        "verdict": null,
        "percentile": null,
        "subs": []
      },
      {
        "name": "Offensive Rebounds (Put Backs)",
        "poss": 5,
        "timePct": 7.1,
        "pps": 1.0,
        "efg": 33.3,
        "verdict": null,
        "percentile": null,
        "subs": []
      },
      {
        "name": "Handoffs",
        "poss": 4,
        "timePct": 5.7,
        "pps": 0.75,
        "efg": 50.0,
        "verdict": null,
        "percentile": null,
        "subs": []
      },
      {
        "name": "Miscellaneous Plays",
        "poss": 4,
        "timePct": 5.7,
        "pps": 0.25,
        "efg": null,
        "verdict": null,
        "percentile": null,
        "subs": []
      },
      {
        "name": "Off Screen",
        "poss": 2,
        "timePct": 2.9,
        "pps": 0.0,
        "efg": 0.0,
        "verdict": null,
        "percentile": null,
        "subs": []
      },
      {
        "name": "P&R Ball Handler",
        "poss": 1,
        "timePct": 1.4,
        "pps": 1.0,
        "efg": null,
        "verdict": null,
        "percentile": null,
        "subs": []
      },
      {
        "name": "Post-Up",
        "poss": 1,
        "timePct": 1.4,
        "pps": 2.0,
        "efg": null,
        "verdict": null,
        "percentile": null,
        "subs": []
      },
      {
        "name": "Isolation",
        "poss": 0,
        "timePct": 0.0,
        "pps": null,
        "efg": null,
        "verdict": null,
        "percentile": null,
        "subs": []
      }
    ],
    "shotTypes": [
      {
        "name": "Jump Shot",
        "poss": 24,
        "timePct": 51.1,
        "pps": 0.63,
        "efg": 31.3,
        "verdict": "Poor",
        "percentile": 10,
        "subs": [
          {
            "name": "Catch and Shoot",
            "poss": 24,
            "timePct": 100.0,
            "pps": 0.63,
            "efg": 31.3,
            "subs": [
              {
                "name": "Guarded",
                "poss": 12,
                "timePct": 50.0,
                "pps": 1.0,
                "efg": 50.0
              },
              {
                "name": "Unguarded",
                "poss": 12,
                "timePct": 50.0,
                "pps": 0.25,
                "efg": 12.5
              }
            ]
          },
          {
            "name": "Dribble Jumper",
            "poss": 0,
            "timePct": 0.0,
            "pps": null,
            "efg": null,
            "subs": []
          },
          {
            "name": "Early Jumper",
            "poss": 0,
            "timePct": 0.0,
            "pps": null,
            "efg": null,
            "subs": []
          }
        ]
      },
      {
        "name": "At Rim",
        "poss": 19,
        "timePct": 40.4,
        "pps": 1.47,
        "efg": 73.7,
        "verdict": "Excellent",
        "percentile": 95,
        "subs": [
          {
            "name": "Layup",
            "poss": 15,
            "timePct": 78.9,
            "pps": 1.47,
            "efg": 73.3,
            "subs": []
          },
          {
            "name": "Dunk",
            "poss": 4,
            "timePct": 21.1,
            "pps": 1.5,
            "efg": 75.0,
            "subs": []
          },
          {
            "name": "Tip",
            "poss": 0,
            "timePct": 0.0,
            "pps": null,
            "efg": null,
            "subs": []
          }
        ]
      },
      {
        "name": "Runner",
        "poss": 3,
        "timePct": 6.4,
        "pps": 0.0,
        "efg": 0.0,
        "verdict": null,
        "percentile": null,
        "subs": []
      },
      {
        "name": "Hook",
        "poss": 1,
        "timePct": 2.1,
        "pps": 0.0,
        "efg": 0.0,
        "verdict": null,
        "percentile": null,
        "subs": []
      }
    ],
    "shotZones": {
      "restrictedArea": {
        "volume": 36.2,
        "efg": 70.6,
        "poss": 17
      },
      "paint": {
        "volume": 12.8,
        "efg": 33.3,
        "poss": 6
      },
      "midrange": {
        "volume": 0.0,
        "efg": null,
        "poss": 0
      },
      "beyondArc": {
        "volume": 51.1,
        "efg": 31.2,
        "poss": 24
      }
    },
    "archetype": "High-Energy 5 / Rebounder",
    "analysis": [
      "20.9 DR%",
      "1.471 PPS on Cuts (Excellent)",
      "20.8% from 3 and 61.8% FT, but must consider small minutes sample"
    ]
  }
};
